import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai";
import profile from "../public/profile.png";
import logo from "../public/jec_logo_1.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Joshua Emmanuel Capito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 font-roboto">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <Image src={logo} width={"120"} height={"120"} />
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume/CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-5">
            <h2 className="text-5xl py-2 text-gray-800 font-medium dark:text-teal-400 md:text-8xl ">
              Welcome to my Portfolio
            </h2>
            {/* <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and Designer
            </h3>
            <h3 className="text-sm py-2 dark:text-white md:text-xl">
              ...and an aspiring DevOps Engineer!
            </h3> */}
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Web developer • UX/UI designer • DevOps engineer in training.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="www.google.com"
                className="text-center shadow-lg p-2 rounded-xl  dark:bg-white"
              >
                <AiFillGithub />
              </a>
              <a
                href="www.google.com"
                className="text-center shadow-lg p-2 rounded-xl  dark:bg-white"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="www.google.com"
                className="text-center shadow-lg p-2 rounded-xl  dark:bg-white"
              >
                <AiFillInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                src={profile}
                layout="fill"
                objectFit="cover"
                className="transform h-64 shadow-lg bg-gray-100 w-80 transition duration-500 hover:scale-125 hover:bg-teal-300 flex justify-center items-center"
              />
            </div>
          </div>
        </section>
        
        <section>
          <div className="p-10 py-20">
            <h3 className="text-5xl py-1 dark:text-white md:text-7xl text-gray-800 relative group">
              👋 Hi! I'm <span className="text-teal-500">Josh</span>
              <span className="absolute -bottom-1 left-0 w-0 h-2 bg-teal-400 transition-all group-hover:w-full"></span>
            </h3>
            <p className="text-2xl py-2 my-10 leading-12 text-gray-800 dark:text-gray-200 md:text-6xl">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
              <br />
              <br />
              Lorem ipsum dolor, sit amet consectetur adipisicing elit.
              Obcaecati esse et dignissimos harum architecto aliquam?
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-4xl font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2 text-2xl">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-3xl font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2 text-2xl">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-3xl font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2 text-2xl">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
            </div>
          </div>
        </section>
        <section className=" p-10 py-10">
          <div>
            <hr />
            <h3 className="text-3xl font-medium pt-8 pb-2 dark:text-white md:text-6xl">
              Selected Works
            </h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
